#!/usr/bin/env python3
"""Turn the test vectors of tools/cgusb_host.py into a C header.

The generated header is what lets test_cgusb.c prove that the C encoder in
components/cgusb and the Python reference produce the same bytes (D-007).
It is generated on every test run and is not committed, so the two can never
drift apart unnoticed.

    python test/host/gen_vectors.py test/host/build/vectors.h
"""
from __future__ import annotations

import pathlib
import sys

HERE = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent.parent / "tools"))

import cgusb_host  # noqa: E402


def c_bytes(data: bytes) -> str:
    if not data:
        # C has no zero length array, and the length field says it is empty.
        return "{0}"
    return "{" + ", ".join(f"0x{b:02X}" for b in data) + "}"


def main(argv: list[str]) -> int:
    out_path = pathlib.Path(argv[0]) if argv else HERE / "build" / "vectors.h"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    vectors = cgusb_host.build_vectors()

    lines = [
        "/* Generated by test/host/gen_vectors.py from tools/cgusb_host.py.",
        " * Do not edit, and do not commit: it is rebuilt on every test run so",
        " * that the C encoder and the Python reference cannot drift apart. */",
        "#pragma once",
        "",
        "#include <stddef.h>",
        "#include <stdint.h>",
        "",
        "typedef struct {",
        "    const char *name;",
        "    uint8_t type;",
        "    const uint8_t *payload;",
        "    size_t payload_len;",
        "    const uint8_t *frame;",
        "    size_t frame_len;",
        "    uint16_t crc;",
        "} cgusb_vector_t;",
        "",
    ]

    for index, vector in enumerate(vectors):
        payload = bytes.fromhex(vector["payload"])
        frame = bytes.fromhex(vector["frame"])
        lines.append(f"static const uint8_t cgusb_vec_payload_{index}[] = {c_bytes(payload)};")
        lines.append(f"static const uint8_t cgusb_vec_frame_{index}[] = {c_bytes(frame)};")
    lines.append("")

    lines.append(f"#define CGUSB_VECTOR_COUNT {len(vectors)}u")
    lines.append("")
    lines.append("static const cgusb_vector_t cgusb_vectors[CGUSB_VECTOR_COUNT] = {")
    for index, vector in enumerate(vectors):
        payload_len = len(bytes.fromhex(vector["payload"]))
        frame_len = len(bytes.fromhex(vector["frame"]))
        lines.append(
            f'    {{"{vector["name"]}", 0x{vector["type"]:02X}, '
            f"cgusb_vec_payload_{index}, {payload_len}u, "
            f"cgusb_vec_frame_{index}, {frame_len}u, 0x{vector['crc']:04X}}},"
        )
    lines.append("};")
    lines.append("")

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"gen_vectors: {len(vectors)} vectors to {out_path}")
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
